### ISSUE TITLE
Add dark and light only colors for theme switcher

### ISSUE THREAD

**Issue by ngblaylock** [ngblaylock/bootstrap-extensions#24]
If you have the theme toggle button on a background that is always light or dark, you need to keep it white/black no matter the theme. This should work:

```scss
$theme-switch-size: $spacer * 2 !default;

@function sun-icon($color) {
  @return #{escape-svg(
      url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'><path fill='#{$color}' d='m11 3c0-0.55228 0.4477-1 1-1s1 0.44772 1 1v3c0 0.55228-0.4477 1-1 1s-1-0.44772-1-1v-3zm5 9c0 2.2091-1.7908 4-4 4-2.2091 0-4-1.7909-4-4 0-2.2091 1.7909-4 4-4 2.2092 0 4 1.7909 4 4zm4.6602-4.9999c-0.2762-0.47829-0.8878-0.64217-1.3661-0.36603l-2.598 1.5c-0.4783 0.27615-0.6422 0.88774-0.3661 1.366 0.2762 0.47829 0.8878 0.64214 1.3661 0.36602l2.598-1.5c0.4783-0.27614 0.6422-0.88773 0.3661-1.366zm-16.954 1.3659c-0.47829-0.27615-0.64217-0.88774-0.36602-1.366 0.27614-0.47829 0.88773-0.64217 1.366-0.36602l2.5981 1.5c0.47829 0.27614 0.64217 0.88773 0.36602 1.366-0.27614 0.47829-0.88773 0.64216-1.366 0.36603l-2.5981-1.5zm8.2941 8.634c-0.5523 0-1 0.4477-1 1v3c0 0.5523 0.4477 1 1 1s1-0.4477 1-1v-3c0-0.5523-0.4477-1-1-1zm-5.6961-2.866c0.47829-0.2761 1.0899-0.1122 1.366 0.3661 0.27614 0.4783 0.11226 1.0898-0.36603 1.366l-2.5981 1.5c-0.47829 0.2761-1.0899 0.1123-1.366-0.366s-0.11227-1.0899 0.36602-1.3661l2.5981-1.5zm10.026 0.3659c-0.2762 0.4783-0.1123 1.0899 0.366 1.3661l2.5981 1.5c0.4783 0.2761 1.0899 0.1122 1.366-0.3661 0.2762-0.4783 0.1123-1.0898-0.366-1.366l-2.5981-1.5c-0.4783-0.2761-1.0899-0.1123-1.366 0.366z'/></svg>")
    )};
}

@function moon-icon($color) {
  @return #{escape-svg(
      url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'><path fill='#{$color}' d='m21.185 15.962c0.1289-0.2986-0.1782-0.5884-0.4862-0.4841-0.9994 0.3384-2.0761 0.5227-3.1982 0.5227-5.2468 0-9.5001-4.0294-9.5001-9 0-1.3591 0.31797-2.6478 0.88728-3.803 0.1516-0.30761-0.12642-0.66704-0.4469-0.54494-3.7654 1.4346-6.4406 5.0789-6.4406 9.348 0 5.5228 4.4772 10 10 10 4.1156 0 7.6504-2.4862 9.1847-6.0386zm-4.3754-5.6917c-0.0373-0.0124-0.0666-0.0417-0.0791-0.079l-0.6116-1.835c-0.038-0.11396-0.1992-0.11396-0.2372 0l-0.6116 1.835c-0.0125 0.0373-0.0418 0.0666-0.0791 0.079l-1.8349 0.6117c-0.114 0.038-0.114 0.1992 0 0.2372l1.8349 0.6116c0.0373 0.0125 0.0666 0.0417 0.0791 0.0791l0.6116 1.8349c0.038 0.114 0.1992 0.114 0.2372 0l0.6116-1.8349c0.0125-0.0374 0.0418-0.0666 0.0791-0.0791l1.8349-0.6116c0.114-0.038 0.114-0.1992 0-0.2372l-1.8349-0.6117zm-2.329-4.8291c0.0124 0.03733 0.0417 0.06662 0.079 0.07906l1.0849 0.36163c0.114 0.03799 0.114 0.19919 0 0.23717l-1.0848 0.36162c-0.0373 0.01244-0.0666 0.04173-0.0791 0.07906l-0.3616 1.085c-0.038 0.11396-0.1992 0.11396-0.2372 0l-0.3617-1.085c-0.0124-0.03733-0.0417-0.06662-0.079-0.07906l-1.085-0.36167c-0.114-0.03798-0.114-0.19918 0-0.23717l1.085-0.36168c0.0373-0.01244 0.0666-0.04173 0.0791-0.07906l0.3616-1.0848c0.038-0.11396 0.1992-0.11396 0.2372 0l0.3616 1.0849z'/></svg>")
    )};
}

@function system-icon($color) {
  @return #{escape-svg(
      url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'><path fill='#{$color}' d='m4 4c-1.1046 0-2 0.89543-2 2v8c0 1.1046 0.89543 2 2 2h6.75c0.1381 0 0.25 0.1119 0.25 0.25v1.5c0 0.1381-0.1119 0.25-0.25 0.25h-1.75c-0.55228 0-1 0.4477-1 1s0.44772 1 1 1h6c0.5523 0 1-0.4477 1-1s-0.4477-1-1-1h-1.75c-0.1381 0-0.25-0.1119-0.25-0.25v-1.5c0-0.1381 0.1119-0.25 0.25-0.25h6.75c1.1046 0 2-0.8954 2-2v-8c0-1.1046-0.8954-2-2-2h-16zm15.053 2.4736c0.2359-0.11798 0.152-0.47361-0.1118-0.47361h-14.691c-0.13807 0-0.25 0.11193-0.25 0.25v7.3455c0 0.1858 0.19558 0.3067 0.3618 0.2236l14.691-7.3455z' clip-rule='evenodd' fill-rule='evenodd'/></svg>")
    )};
}

$sun-icon-light: sun-icon($body-bg);
$sun-icon-dark: sun-icon($body-color);
$moon-icon-light: moon-icon($body-bg);
$moon-icon-dark: moon-icon($body-color);
$system-icon-light: system-icon($body-bg);
$system-icon-dark: system-icon($body-color);

:root,
[data-bs-theme="light"] {
  --#{$prefix}theme-switch-size: #{$theme-switch-size};
  --#{$prefix}theme-switch-bg-rgb: var(--#{$prefix}body-color-rgb);
  --#{$prefix}light-theme-icon: #{$sun-icon-dark};
  --#{$prefix}dark-theme-icon: #{$moon-icon-light};
  --#{$prefix}system-theme-icon: #{$system-icon-dark};
}

[data-bs-theme="dark"] {
  --#{$prefix}system-theme-icon: #{$system-icon-light};
}

.theme-switch {
  &.theme-switch-dark {
    --#{$prefix}theme-switch-bg-rgb: #{to-rgb($body-color)};
    --#{$prefix}light-theme-icon: #{$sun-icon-dark};
    --#{$prefix}dark-theme-icon: #{$moon-icon-dark};
    --#{$prefix}system-theme-icon: #{$system-icon-dark};
  }
  &.theme-switch-light {
    --#{$prefix}theme-switch-bg-rgb: #{to-rgb($body-bg)};
    --#{$prefix}light-theme-icon: #{$sun-icon-light};
    --#{$prefix}dark-theme-icon: #{$moon-icon-light};
    --#{$prefix}system-theme-icon: #{$system-icon-light};
  }
}

input.theme-switch[type="checkbox"] {
  appearance: none;
  width: var(--#{$prefix}theme-switch-size);
  height: var(--#{$prefix}theme-switch-size);
  background-color: rgba(var(--#{$prefix}theme-switch-bg-rgb), 0.05);
  background-image: var(--#{$prefix}light-theme-icon);
  background-repeat: no-repeat;
  background-position: center;
  background-size: 75%;
  border-radius: $border-radius-pill;
  cursor: pointer;
  background-color: rgba(var(--#{$prefix}theme-switch-bg-rgb), 0.05);
  transition: background 0.2s;
  &:hover {
    background-color: rgba(var(--#{$prefix}theme-switch-bg-rgb), 0.09);
  }
  &:focus {
    background-color: rgba(var(--#{$prefix}theme-switch-bg-rgb), 0.12);
  }
  &:checked {
    background-image: var(--#{$prefix}dark-theme-icon);
  }
  &:indeterminate {
    background-image: var(--#{$prefix}system-theme-icon);
  }
  [data-bs-theme="dark"] & {
    &:indeterminate {
      background-image: var(--#{$prefix}system-theme-icon);
    }
  }
}

```
